name: Deploy to IPFS via Pinata
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Pinata Web3 SDK
        run: npm install pinata-web3

      - name: Upload to Pinata
        run: |
          node -e "
          const { Pinata } = require('pinata-web3');
          const pinata = new Pinata({ pinataApiKey: process.env.PINATA_API_KEY, pinataSecretApiKey: process.env.PINATA_API_SECRET });

          const fs = require('fs');
          const fileStream = fs.createReadStream('./src/index.html');

          pinata.pinFileToIPFS(fileStream).then(result => {
            console.log('File pinned successfully:', result);
          }).catch(error => {
            console.error('Error pinning file:', error);
          });
          "
        env:
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_API_SECRET: ${{ secrets.PINATA_API_SECRET }}
